export const FETCH_RESERVATIONS_START = "FETCH_RESERVATIONS_START";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const FETCH_RESERVATIONS_FAILURE = "FETCH_RESERVATIONS_FAILURE";
export const SET_RESERVATIONS_TEXT_FILTER = "SET_TEXT_FILTER";
